apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: adam2696/ic-webapp:1.0
        env:
        - name: ODOO_URL
          value: "http://odoo:8069"  # Remplacez par l'URL de votre application Odoo
        - name: PGADMIN_URL
          value: "http://pgadmin:80"  # Remplacez par l'URL de votre application pgAdmin
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  namespace: icgroup
spec:
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
